version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-laravel-10
        restart: always
        tty: true
        ports:
            - "8000:3000"
            # - "9027:9000"
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel
            
    # db mysql
    db:
        image: mysql:latest
        platform: linux/x86_64
        container_name: mysql
        # restart: unless-stopped
        environment:
            MYSQL_DATABASE: basicus
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx
        # restart: unless-stopped
        ports:
            - "80:80"
            # - "8000:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
volumes:
  db:
    driver: local